### ISSUE TITLE
5.4.78-2

### ISSUE THREAD

**Issue by akhan23wgu** [kiler129/relax-intel-rmrr#3]
So I accidentally updated my kernel to 5.4.78-2. Would you have any recommendations for that update path?

**Comment by kiler129** [comment]
Is your system a Proxmox or a Debian 10?

If so you can grab the newest release and reinstall 5.4.86-1 from the releases page: https://github.com/kiler129/relax-intel-rmrr/releases

**Comment by kiler129** [comment]
Closed due to no response. Feel free to reopen it @akhan23wgu if you need to.
