### ISSUE TITLE
Proxmox 6.3-4

### ISSUE THREAD

**Issue by RedEpicness** [kiler129/relax-intel-rmrr#4]
Hello, I found this when trying to passthrough my 750 Ti on a HP DL 380 G7. Issue is that I am running proxmox version 6.3-4 and the latest released packages are for 6.3-2. Would it still be fine to update to the latest released packages even though they are kernel version 5.4.86 whereas my current install is 5.4.98? I would assume it couldn't be a big issue, but I saw you being responsive on the other issue so I rather ask. :)

**Comment by kiler129** [comment]
Hi!

I'm sorry I missed your issue for couple of days 🤭 

Most of the time Proxmox keeps up with (rather fast-paced) Ubuntu Focal kernel releases and don't make any major modifications. In other words using kernel which is a within the same minor (second number in the version string) is perfectly fine between versions of Proxmox. In fact I have couple of installations with newer and older kernels vs. what Proxmox ships with a particular version of the whole OS, so you can use 5.4.86 with 6.3-4.

I compiled & tested the newest kernel 5.4.101-1 (as of yesterday): https://github.com/kiler129/relax-intel-rmrr/releases/tag/v1.0.3 - it works perfectly with 6.3-4.

Let me know if this fully answers your question ;)

**Comment by RedEpicness** [comment]
Hey, no worries I just ended up compiling myself and I finally can passthrough my GPU, after fixing the vBios for the gpu. I forgot to close the issue after i compiled it myself. This is good to know in advance though so I don't have to recompile every time I want to update haha. 

Anyway thanks a lot for making this project it really helped me out!
